AWSTemplateFormatVersion: 2010-09-09
Description: Setup ECR repo for SharedID.
Parameters:
  RepoName:
    Type: String
    Default: SharedID
Resources:
  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepoName
Outputs:
  Arn:
    Value: !GetAtt Repository.Arn
